### ISSUE TITLE
Reinvention of square wheel

### ISSUE THREAD

**Issue by ojhaujjwal** [misarji/zend-oauth2#1]
Sorry to say but this module is just a **reinvention of square wheel**. There are much better oauth2 client libraries available like this one: https://github.com/thephpleague/oauth2-client . And there is a Zend Framework 2 module too : https://github.com/hrevert/HtLeagueOauthClientModule

**Comment by voidz0r** [comment]
@ojhaujjwal Just because you are a contributor of these packages doesn't mean you are authorized to judge other people's work and spamming around your sh*t. 
I don't care if these repos are better and i don't care about your opinion so your comment is useless. Just connect your brain with your fingers before writing.

**Comment by ojhaujjwal** [comment]
I was just trying to do author a favour by tellling him that there are much better options out there. Who the hell are you and why should I care about you caring or not. I don't care if you think these comment are useless. I was expressing my opinions to the author of this module. How about you connect your brain with your fingers before writing?

**Comment by ojhaujjwal** [comment]
@voidz0r There are much better ways to deny people's opinions. Shit, I just wasted important few minutes of my life trying to help bastards!
